[package]
name = "square_sum_module"
version = "0.1.0"
edition = "2021"

[lib]
name = "square_sum_module"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.24.0"
features = ["extension-module"]
